/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlayRouteImport } from './routes/play'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as GamesRouteImport } from './routes/games'
import { Route as DndRouteImport } from './routes/dnd'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as YamsIndexRouteImport } from './routes/yams.index'
import { Route as YamsCodeRouteImport } from './routes/yams.$code'
import { Route as RoomCodeRouteImport } from './routes/room.$code'

const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const DndRoute = DndRouteImport.update({
  id: '/dnd',
  path: '/dnd',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const YamsIndexRoute = YamsIndexRouteImport.update({
  id: '/yams/',
  path: '/yams/',
  getParentRoute: () => rootRouteImport,
} as any)
const YamsCodeRoute = YamsCodeRouteImport.update({
  id: '/yams/$code',
  path: '/yams/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomCodeRoute = RoomCodeRouteImport.update({
  id: '/room/$code',
  path: '/room/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dnd': typeof DndRoute
  '/games': typeof GamesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/play': typeof PlayRoute
  '/room/$code': typeof RoomCodeRoute
  '/yams/$code': typeof YamsCodeRoute
  '/yams/': typeof YamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dnd': typeof DndRoute
  '/games': typeof GamesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/play': typeof PlayRoute
  '/room/$code': typeof RoomCodeRoute
  '/yams/$code': typeof YamsCodeRoute
  '/yams': typeof YamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dnd': typeof DndRoute
  '/games': typeof GamesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/play': typeof PlayRoute
  '/room/$code': typeof RoomCodeRoute
  '/yams/$code': typeof YamsCodeRoute
  '/yams/': typeof YamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dnd'
    | '/games'
    | '/leaderboard'
    | '/play'
    | '/room/$code'
    | '/yams/$code'
    | '/yams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dnd'
    | '/games'
    | '/leaderboard'
    | '/play'
    | '/room/$code'
    | '/yams/$code'
    | '/yams'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dnd'
    | '/games'
    | '/leaderboard'
    | '/play'
    | '/room/$code'
    | '/yams/$code'
    | '/yams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DndRoute: typeof DndRoute
  GamesRoute: typeof GamesRoute
  LeaderboardRoute: typeof LeaderboardRoute
  PlayRoute: typeof PlayRoute
  RoomCodeRoute: typeof RoomCodeRoute
  YamsCodeRoute: typeof YamsCodeRoute
  YamsIndexRoute: typeof YamsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dnd': {
      id: '/dnd'
      path: '/dnd'
      fullPath: '/dnd'
      preLoaderRoute: typeof DndRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yams/': {
      id: '/yams/'
      path: '/yams'
      fullPath: '/yams/'
      preLoaderRoute: typeof YamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yams/$code': {
      id: '/yams/$code'
      path: '/yams/$code'
      fullPath: '/yams/$code'
      preLoaderRoute: typeof YamsCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$code': {
      id: '/room/$code'
      path: '/room/$code'
      fullPath: '/room/$code'
      preLoaderRoute: typeof RoomCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DndRoute: DndRoute,
  GamesRoute: GamesRoute,
  LeaderboardRoute: LeaderboardRoute,
  PlayRoute: PlayRoute,
  RoomCodeRoute: RoomCodeRoute,
  YamsCodeRoute: YamsCodeRoute,
  YamsIndexRoute: YamsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
