ALTER TABLE public.games REPLICA IDENTITY FULL;
ALTER TABLE public.game_players REPLICA IDENTITY FULL;
ALTER TABLE public.rounds REPLICA IDENTITY FULL;
ALTER TABLE public.game_events REPLICA IDENTITY FULL;
ALTER TABLE public.bids REPLICA IDENTITY FULL;
ALTER TABLE public.yams_games REPLICA IDENTITY FULL;
ALTER TABLE public.yams_players REPLICA IDENTITY FULL;
ALTER TABLE public.yams_events REPLICA IDENTITY FULL;